---
kind: pipeline
type: docker
name: goenv

steps:
  - name: build
    pull: if-not-exists
    image: golang:alpine
    commands:
      - chmod +x build.sh
      - ./build.sh
  - name: upload
    image: hkccr.ccs.tencentyun.com/xiaoqidun/gocos
    settings:
      secret_id:
        from_secret: cos_secret_id
      secret_key:
        from_secret: cos_secret_key
      bucket_url:
        from_secret: cos_bucket_url
      source: release/
      target: product/goenv
      strip_prefix: release/

---
kind: pipeline
type: docker
name: docker

steps:
  - name: build
    pull: if-not-exists
    image: alpine
    commands:
      - wget -q -T 180 https://dl.google.com/android/repository/android-ndk-r23-linux.zip
      - unzip -q android-ndk-r23-linux.zip
      - rm -f android-ndk-r23-linux.zip
  - name: docker1
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: hkccr.ccs.tencentyun.com/xiaoqidun/goenv
      username:
        from_secret: docker_username1
      password:
        from_secret: docker_password1
      dockerfile: Dockerfile
  - name: docker2
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: hkccr.ccs.tencentyun.com/xiaoqidun/goenv
      registry: hkccr.ccs.tencentyun.com
      username:
        from_secret: docker_username2
      password:
        from_secret: docker_password2
      dockerfile: Dockerfile