---
kind: pipeline
type: docker
name: default
node:
  region: hk
steps:
  - name: build
    pull: if-not-exists
    image: debian
    commands:
      - wget -4 -q -T 180 https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
      - unzip -q android-ndk-r25c-linux.zip
      - rm -f android-ndk-r25c-linux.zip
  - name: docker-cn
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: ccr.ccs.tencentyun.com/xiaoqidun/goenv
      registry: ccr.ccs.tencentyun.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: DockerfileCN
  - name: docker-hk
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: hkccr.ccs.tencentyun.com/xiaoqidun/goenv
      registry: hkccr.ccs.tencentyun.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: DockerfileHK