kind: pipeline
type: docker
name: default

steps:
  - name: build
    pull: if-not-exists
    image: alpine
    commands:
      - wget -q -T 180 https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
      - unzip -q android-ndk-r21b-linux-x86_64.zip
  - name: docker
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: xiaoqidun/goenv
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile