---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    pull: if-not-exists
    image: alpine
    commands:
      - wget -q -T 180 https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
      - unzip -q android-ndk-r25c-linux.zip
      - rm -f android-ndk-r25c-linux.zip
  - name: docker-hk
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: hkccr.ccs.tencentyun.com/xiaoqidun/goenv
      registry: hkccr.ccs.tencentyun.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
  - name: docker-cn
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: ccr.ccs.tencentyun.com/xiaoqidun/goenv
      registry: ccr.ccs.tencentyun.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: DockerfileCN