---
kind: pipeline
type: docker
name: goenv

steps:
  - name: build
    pull: if-not-exists
    image: golang:alpine
    commands:
      - chmod +x build.sh
      - ./build.sh
  - name: upload
    pull: if-not-exists
    image: plugins/s3
    settings:
      bucket:
        from_secret: minio_bucket
      access_key:
        from_secret: minio_access_key
      secret_key:
        from_secret: minio_secret_key
      source: release/*
      strip_prefix: release/
      target: product/goenv
      path_style: true
      endpoint: https://minio.aite.xyz

---
kind: pipeline
type: docker
name: docker

steps:
  - name: build
    pull: if-not-exists
    image: alpine
    commands:
      - wget -q -T 180 https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
      - unzip -q android-ndk-r21b-linux-x86_64.zip
  - name: docker
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: xiaoqidun/goenv
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile